plugins {
    id 'com.android.application'
}

android {
    namespace 'mg.hira.vavaka.fiaram.testbuild'
    compileSdk 35

    defaultConfig {
        applicationId 'mg.hira.vavaka.fiaram.testbuild'
        minSdk 19
        targetSdk 30
        versionCode 123
        versionName '1.2.3-test-logo'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = 'HIRA_VAVAKA_FIARAM_v1.2.3_TEST_LOGO.apk'
        }
    }
}
