plugins {
    id 'com.android.application'
}

android {
    namespace 'mg.hira.vavaka.fiaram.testbuild'
    compileSdk 35

    defaultConfig {
        // Nouveau package pour éviter le conflit de signature avec les anciennes APK de test
        applicationId 'mg.hira.vavaka.fiaram.installfix124'
        minSdk 19
        targetSdk 30
        versionCode 124
        versionName '1.2.4-install-fix'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = 'HIRA_VAVAKA_FIARAM_v1.2.4_INSTALL_FIX.apk'
        }
    }
}
